# Generated by Django 5.2.8 on 2025-12-16 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('github_profile', models.URLField(blank=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills.')),
                ('technologies', models.TextField(blank=True, help_text='Comma-separated technologies.', null=True)),
                ('preferred_roles', models.TextField(blank=True, help_text='Preferred job roles, comma-separated.', null=True)),
                ('preferred_locations', models.TextField(blank=True, help_text='Preferred locations, comma-separated.', null=True)),
                ('job_seniority', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='junior', max_length=20, null=True)),
                ('job_type_preference', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('office', 'Office')], default='remote', max_length=20, null=True)),
                ('industry_preference', models.CharField(blank=True, help_text="Industry preference, e.g. 'Fintech', 'AI', 'E-commerce'", max_length=100, null=True)),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('experience', models.TextField(blank=True)),
                ('education', models.TextField(blank=True)),
                ('languages', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
