# Generated by Django 5.2.7 on 2025-11-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='experience_years',
            field=models.IntegerField(blank=True, default=None, help_text='Number of years of experience in field', null=True),
        ),
    ]
