# Generated by Django 5.2.8 on 2025-12-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='industry_preference',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='job_seniority',
            field=models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='junior', max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='job_type_preference',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('office', 'Office')], default='remote', max_length=20),
        ),
        migrations.AlterField(
            model_name='cv',
            name='preferred_locations',
            field=models.TextField(blank=True, default='', help_text='Comma-separated locations.'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='preferred_roles',
            field=models.TextField(blank=True, default='', help_text='Comma-separated preferred roles.'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='Comma-separated skills.'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='technologies',
            field=models.TextField(blank=True, default='', help_text='Comma-separated technologies.'),
        ),
    ]
