# Generated by Django 5.2.7 on 2025-11-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cv_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
