# Generated by Django 5.2.8 on 2025-12-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_cv_industry_preference_alter_cv_job_seniority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='experience_years',
            field=models.IntegerField(null=True),
        ),
    ]
