# Generated by Django 5.2.8 on 2025-12-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_cv_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
        migrations.AddField(
            model_name='cv',
            name='preferred_locations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='preferred_roles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='technologies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cv',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='languages',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
