# Generated by Django 5.2.8 on 2025-12-04 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cv_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='industry_preference',
            field=models.CharField(blank=True, help_text="Industry preference, e.g. 'Fintech', 'AI', 'E-commerce'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='job_seniority',
            field=models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='junior', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cv',
            name='job_type_preference',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('office', 'Office')], default='remote', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='preferred_locations',
            field=models.TextField(blank=True, help_text='Preferred locations, comma-separated.', null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='preferred_roles',
            field=models.TextField(blank=True, help_text='Preferred job roles, comma-separated.', null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills.'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='technologies',
            field=models.TextField(blank=True, help_text='Comma-separated technologies.', null=True),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
