# Generated by Django 5.2.7 on 2025-11-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('job_url', models.URLField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
