# Generated by Django 5.2.7 on 2025-11-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='atributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
