# Generated by Django 5.2.7 on 2025-11-08 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0002_job_atributes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='atributes',
            new_name='attributes',
        ),
    ]
