# Generated by Django 5.2.7 on 2025-11-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0003_rename_atributes_job_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_scraped',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
