# Generated by Django 5.2.7 on 2025-11-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0004_job_date_posted_alter_job_date_scraped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_scraped',
            new_name='date_last_seen',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=10),
        ),
    ]
