# Generated by Django 5.2.8 on 2025-12-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0005_rename_date_scraped_job_date_last_seen_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
